name: Generate ASCII Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files
        run: ls -al

      - name: Execute shell script to generate ASCII art
        run: ./ascii_script.sh
          
