name: Testing Variable Secrets

# on: push
# on: 
#   schedule:
#     - cron: '*/1 * * * *' # This will run the workflow every hour

on: workflow_dispatch # This allows you to manually trigger the workflow from the GitHub Actions tab

# Environment variables can be defined at the workflow level, job level, or step level. 
# They can also be set using secrets, which are encrypted environment variables that you create in your repository settings. 
# In this example, we will define some environment variables and use secrets to store sensitive information like Docker credentials.

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $CONTAINER_REGISTRY

      - name: Docker publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    concurrency:
      group: deploy-group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run: |
          echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
          sleep 10 # Simulate some deployment time